### ISSUE TITLE
Extra attributes

### ISSUE THREAD

**Issue by RushabhJoshi** [badsyntax/handlebars-form-helpers#3]
sorry,
but there is no help for it
How do I add form-control class in elements?

**Comment by RushabhJoshi** [comment]
My bad.
problem solved

**Comment by badsyntax** [comment]
Can you provide an example of how you did this?

**Comment by RushabhJoshi** [comment]
Thank you for the replay,

thats what i wrote. 
{{select "duration" durations duration class="form-control"}}

initialy i wasn't aware how to set class attr.

**Comment by kolarski** [comment]
This should be added to the documentation. Its useful information!
